### ISSUE TITLE
 Error in jAMM: conditional mediation

### ISSUE THREAD

**Issue by MAgojam** [mcfanda/jamm#10]
Hi, Marcello.

I tried the jAMM v0.0.5 module in jamovi v0.9.5.8 with your example for "Conditional Mediation" and data from (Muller, Judd, Yzerbyt, 2005).
If I enter the **prime** dichotomous variable in the **Factors field**, I receive the following error (see also 1_ScreenShot):
**could not find function "mi.initContrastCode"**
![1_screenshot](https://user-images.githubusercontent.com/36552289/48674033-66d1d380-eb48-11e8-9dbc-c05846944bd7.PNG)

If I enter the **prime** dichotomous variable in the **Covariates field**, the analysis ends successfully (see also 2_ScreenShot).

![2_screenshot](https://user-images.githubusercontent.com/36552289/48674060-a1d40700-eb48-11e8-8f75-56a6ed84dcbe.PNG)

Thank you for your time.
Cheers,
Maurizio

**Comment by mcfanda** [comment]
Hi, did the new version solved the issue?

**Comment by MAgojam** [comment]
Hi, Marcello.
With version 0.0.6 the problem has been solved.
Thank you so much.

Cheers,
Maurizio
