### ISSUE TITLE
Error when "dummy coding"

### ISSUE THREAD

**Issue by SvenHeimbuch** [mcfanda/jamm#12]
jamovi version: 0.9.5.11 (flatpak)
jamm version: 0.0.6 (from binaries)
testdata: airquality.csv (R data sets from jamovi)

I'm getting the same error on every data set I've tested when I'm selecting "dummy" as factor coding.

![dummy_error](https://user-images.githubusercontent.com/27767378/49433524-8f95d200-f7b2-11e8-9906-82df7c7a58aa.png)

**Comment by mcfanda** [comment]
Dummy and Simple are equivalent but for the reference they create. Dummy make the mean of the first group the reference group, Simple makes the sample average. In mediation this difference has almost never practical consequence, so I'm inclined to remove "dummy" as a coding system. One can use "simple"

**Comment by mcfanda** [comment]
Anyway, version 0.0.7 fixes the bug (see master on github/jaam) or the binaries repo.

**Comment by SvenHeimbuch** [comment]
I agree in principle, since these codings do not change the regression estimates. It has only an influence on the intercept, but that might be irrelevant for real application. I was just used to use dummy coding. That's why I tried it out and reported this smallish issue. :-)
