### ISSUE TITLE
No menu entry for jAMM in jamovi flatpak

### ISSUE THREAD

**Issue by SvenHeimbuch** [mcfanda/jamm#9]
I was able to compile the jamm.jmo for jamovi flatpak version. It appears to be correctly installed into the library. But the module does not appear in the menu. I also tried to sideload the .jmo, but without any luck.

![screenshot from 2018-11-16 15-38-13](https://user-images.githubusercontent.com/27767378/48627771-b46a0700-e9b5-11e8-87aa-c78ecabdc63b.png)

**Comment by SvenHeimbuch** [comment]
Just to be clear, an entry under the "Linear Models" menu does also not appear in the Linux flatpak version. It only worked on a Windows machine for me.

**Comment by mcfanda** [comment]
Wow, that's strange because I only tested this module in linux flatpak and it works fine. Can you share the jmo that you produced so I can reproduce the error? thanks

**Comment by mcfanda** [comment]
Hi, I just updated jamovi flatpak to 0.9.5.9 and installed jamm from sideload, and it seems to work (at least the menu is there). Would you like to try my .jmo file and see if the problem still occurs? Here is the link 
https://github.com/mcfanda/binaries
